### ISSUE TITLE
Tailwind

### ISSUE THREAD

**Issue by macrigiuseppe** [glromeo/esbuild-sass-plugin#101]
Hello,
the plugin is really useful. I am trying to integrate esbuild with tailwind pipeline. Can I leverage this plugin? do you have any doc/example?

Thank you

**Comment by glromeo** [comment]
This is not an issue, if you want to open a discussion there's the page for it.
I don't know much about tailwind but I can see that it can be used as a PostCSS plugin.

**Comment by macrigiuseppe** [comment]
@glromeo what's the page for the discussion?
