### ISSUE TITLE
Problem with importing Sass package that uses webpack style imports internally

### ISSUE THREAD

**Issue by klaustopher** [glromeo/esbuild-sass-plugin#102]
I am trying to add [tabler](https://github.com/tabler/tabler) to my project that is using `esbuild`. As I want to hook into their scss files, I'm not importing the `dist` files, but want to import the scss files.

Unfortunately they are using webpack style imports (`~bootstrap/scss/functions`) inside their scss files. See i.e. https://github.com/tabler/tabler/blob/dev/src/scss/_bootstrap-config.scss

Running `esbuild` when importing this file gives me an error:

```
✘ [ERROR] [plugin sass-plugin] Can't find stylesheet to import.
  ╷
1 │ @import "~bootstrap/scss/functions";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/@tabler/core/src/scss/_config.scss 1:9  @import
  node_modules/@tabler/core/src/scss/_core.scss 1:9    @import
  @tabler/core/src/scss/tabler.scss 1:9                @import
  styles/application.scss 1:9                          root stylesheet
```

I have hooked a debugger into the [`canonicalize`](https://github.com/glromeo/esbuild-sass-plugin/blob/main/src/render.ts#L101) method in `render.ts` and it looks like the method is only called for my `application.scss` file, but not for any secondary files. 

Unfortunately that's where my abilities to look further into this end. So help is highly appreciated.

I have boiled down my example into the minimal case: https://github.com/klaustopher/tabler-esbuild-sample.

Would be grateful for pointer to help me solve this, without requiring the tabler team to change their code. I guess there are more packages out there, that use those `~` imports out there, eventhough it's not considered good practice anymore.

**Comment by klaustopher** [comment]
Additional info: In version 2.2.6 of this plugin, it used to work, when adding `cssImports: true` as an option: See https://github.com/klaustopher/tabler-esbuild-sample/tree/old-version

**Comment by glromeo** [comment]
Hi Klaus, thank you for the professionalism in raising this issue...I do appreciate that!
I notice you do a source import and that throws you down a rabbit hole which eventually leads to that error.
changing your `application.scss` to 
```
@import "@tabler/core/dist/css/tabler";
```
builds just fine.
My wonderland metaphor is not random... there are so many unexpected things that happen when going down the path of src import with sass that to keep it simple I feel like says just don't do it! 
But I am all ears if you have a valid case for it!

**Comment by klaustopher** [comment]
Hey,

yeah, I know that it would work, if I import the compiled version. Stated so in my initial post.

My use case is, that I want to extend on the classes that are defined in the framework. Basically build my own stuff ontop of it and thus I would line to use the helper functions defined in the framework and bootstrap. If I were using the `dist` version I‘d have to jump through many more hoops to get access to those.

Also, in the linked issue in tabler, somebody posted an example rails app using version 2.2.6 of this plugin here and with this version it used to work importing the src files

**Comment by glromeo** [comment]
Ok, please update to v2.4.1 
if by any chance you turn on quietDeps it would break your build again but I consider that a minor inconvenient
I will ship a fix for that when I am back from my holidays

**Comment by klaustopher** [comment]
Hey, thanks, checked it out and it works. Thank you for the quick fix.
