### ISSUE TITLE
Different alternatives for `type` between Usage and Options section  

### ISSUE THREAD

**Issue by iliocatallo** [glromeo/esbuild-sass-plugin#104]
Hi!

I noticed that the [Usage](https://github.com/glromeo/esbuild-sass-plugin#usage) section reports `style`, `css-text` and `lit-css` as possible alternatives for `type`. On the other hand, the table under [Option](https://github.com/glromeo/esbuild-sass-plugin#options) indicates `css` (as opposed to `css-text`), `style` and `lit-css` as supported variants.

Thank you,
Ilio.

**Comment by glromeo** [comment]
Yup, thank you pointing that out Ilio. Indeed I have to tidy up the README. `css-text` is different from `css` (which delegates to `esbuild` the bundling) it's like `lit-css` but for when you want to just put the text yourself in a shadow dom style.
