### ISSUE TITLE
Failed incremental rebuilds no longer pick up SCSS code changes

### ISSUE THREAD

**Issue by samhuk** [glromeo/esbuild-sass-plugin#105]
I think this has been a bug for a while (>1 year). I'm only getting around to reporting it now as it's very niche and quite difficult to explain.

In short, esbuild-sass-plugin appears to not pick up changes made to fix SCSS code errors when using esbuild's incremental `rebuild()` functionality. This is much easier to explain with code.

Have a basic file structure like so:
```
index.ts
styles.scss
colors.scss
```

index.ts:
```typescript
import './styles.scss'

// ...Typescript code...
```

styles.scss:
```scss
@import './colors.scss';

// ...SCSS code...
```

colors.scss:
```scss
// ...SCSS code...
```

An example build script showing the bug:
```Typescript
import { build } from 'esbuild'
import sassPlugin from 'esbuild-sass-plugin'

const myBuild = async () => {
  const initialBuildResult = await build({ // <-- Successful build
    entryPoints: ['./index.ts'],
    outfile: './build/index.js',
    bundle: true,
    metafile: true,
    incremental: true,
    plugins: [sassPlugin() as unknown as Plugin],
  })
  
  // ...MAKE A SYNTAX ERROR IN colors.scss...
  // ...This could be as simple as adding an illegal character at the end like a '?'...
  await makeSyntaxErrorToColorsScssFile()

  const rebuildResult1 = await initialBuildResult.rebuild() // <-- Unsuccessful build

  // ...FIX SYNTAX ERROR IN colors.scss...
  await fixSyntaxErrorToColorsScssFile()

  const rebuildResult1 = await initialBuildResult.rebuild()
  // ^ Still an unsuccessful build, still complaining about the syntax error we made and then fixed.
}
myBuild()
```

I know that this plugin has some "cache"-related logic, so that would be my first suspicion. Alternatives would be either a bug with esbuild's incremental rebuilding code, or something I'm not doing right.

**Comment by glromeo** [comment]
Thank you @samhuk that was a spot on and helpful issue report!
Please update to v2.4.2

**Comment by samhuk** [comment]
Wow, that was quick! I wasn't sure if my explanation of it was going to be good, it's really hard to explain such a bug that contains so many little details.

I can confirm in my own projects that this change has fixed the bug, too. My hot-reloading now 100% works 😄 

Thank you very much @glromeo !!
