### ISSUE TITLE
Empty sourcesContent

### ISSUE THREAD

**Issue by mistic100** [glromeo/esbuild-sass-plugin#107]
Using this plugin with source maps enabled, the `sourcesContent` array only contains nulls where it shoudl contains the content of each source. Sources content is usefull to have a autonomous source map and not having to also publish the actual source files.

Demo repo : https://github.com/mistic100/test-esbuild-sass (there are two configs for esbuild and tsup, resulting in the same behaviour).

**Input**
```scss
body {
    background: black;
}
```

**Actual output**
```json
{
  "version": 3,
  "sources": ["../src/index.scss"],
  "sourcesContent": [null],
  "mappings": ";AAAA;AACI;;",
  "names": []
}
```

**Expected output**
```json
{
  "version": 3,
  "sources": ["../src/index.scss"],
  "sourcesContent": ["body {\n    background: black;\n}\n"],
  "mappings": ";AAAA;AACI;;",
  "names": []
}
```

https://www.npmjs.com/package/esbuild-plugin-sass does not have this issue

**Comment by glromeo** [comment]
Thank you for providing an example repo that speeded up finding the fix a lot.
Please update to v2.4.3!

**Comment by mistic100** [comment]
That was quick, thank you!
