### ISSUE TITLE
getJSON can't be used due to override

### ISSUE THREAD

**Issue by pc-erin** [glromeo/esbuild-sass-plugin#110]
On [this line](https://github.com/glromeo/esbuild-sass-plugin/blob/7341d2c7864151e8c8161053ce8882fd5327ff98/src/utils.ts#L151), the `getJSON` option gets overridden so we can't do anything with that data if we want to.

Could we add some passthrough code so the external optons can still use that?

```ts
getJSON(cssFilename: string, json: { [name: string]: string }, outputFileName: string): void {
  cssModule = JSON.stringify(json, null, 2)
  option.getJSON?.(cssFilename, json, outputFileName)
}
```

**Comment by glromeo** [comment]
it makes sense... if you rise a PR with that change I will be happy to merge it
