### ISSUE TITLE
Strip `~` from import/use/forward statements

### ISSUE THREAD

**Issue by shellscape** [glromeo/esbuild-sass-plugin#114]
Hey there. Thanks for this plugin.

It's unfortunately common for folks to use a tilde `~` in import statements, which this plugin doesn't yet support. That ends up throwing a build error. Packages like https://www.npmjs.com/package/@ircc-ca/ds-sdc-core use this, and it's so common that webpack's loader accounts for this.

https://github.com/sass/dart-sass/issues/801 covers this as well, and the recommendation is to remove the `~`.

Any chance this could be supported?

**Comment by glromeo** [comment]
~ imports are supported out of the box as you can see here:
https://github.com/glromeo/esbuild-sass-plugin/blob/2703569b381b1cb1733a9ae5cf75d19d0de4cb1d/test/fixture/bootstrap/src/entrypoint.scss#L1
what is not immediate but still supported is to  have css imports using tilde as seen here:
https://github.com/glromeo/esbuild-sass-plugin/issues/74
but also this might help:
https://github.com/glromeo/esbuild-sass-plugin/issues/39

if that still doesn't work feel free to reopen this issue provided an example repo where the ~ import is an issue

**Comment by shellscape** [comment]
I'll put together a repl.it for the failing case I ran into.

**Comment by shellscape** [comment]
@glromeo I believe this has to do with the esbuild `absWorkingDir` setting. This REPL https://replit.com/@shellscape/failing-tilde-esbuild demonstrates the problem.

The build target is in the `target` directory (which repl.it unfortunately puts under the `Packager Files` section).

To run, enter the following commands in the `Shell` terminal window - don't click the `Run` button!

```
yarn
node index.mjs
```

The build config is in the `build.mjs` file. We're telling esbuild that the target is in a separate directory than the execution directory (hence a difference cwd). It appears that `esbuild-sass-plugin` isn't taking that into account and is looking at the cwd `node_modules` and throwing an error.
