### ISSUE TITLE
Please remove node_module from `esbuild-sass-plugin`

### ISSUE THREAD

**Issue by mav-rik** [glromeo/esbuild-sass-plugin#118]
After install `npm i -sD esbuild-sass-plugin` I always get nested `node_modules` dir which leads to TS errors:

![image](https://user-images.githubusercontent.com/20143759/213809925-7c113526-cbe9-47bd-a3b7-4698f5a21f53.png)

Could you please fix that?

**Comment by glromeo** [comment]
v2.6.0 should address you TS errors, node_modules is meant to be there
