### ISSUE TITLE
exclude example in readme does not work, (?! not supported in go

### ISSUE THREAD

**Issue by chee** [glromeo/esbuild-sass-plugin#119]
hey. it seems like the filter regex is meant to be a go regex which means the exclude example doesn't work because it doesn't support `(?!`

**Comment by glromeo** [comment]
Thank you for spotting it! And filling the gaps in my Go knowledge 😄 
`exclude` option is back in v2.7.0 and I also added `external` to facilitate
excluding URLs

**Comment by chee** [comment]
> Thank you for spotting it! And filling the gaps in my Go knowledge 😄 `exclude` option is back in v2.7.0 and I also added `external` to facilitate excluding URLs

Thank-you! that's wonderful
