### ISSUE TITLE
Compatible with esbuild-plugin-pnp?

### ISSUE THREAD

**Issue by onox** [glromeo/esbuild-sass-plugin#12]
I'm having trouble getting your plugin to work when using Yarn 2's Pnp feature. I get a lot of the following errors:

```
> .yarn/cache/sass-npm-1.20.1-bd1594cc3f-16f0ce7a4d.zip/node_modules/sass/sass.dart.js:5241:29: error: [plugin: sass-plugin] MyComponent.scss: no such file or directory
```

when importing Sass with `import styles from "./MyComponent.scss"`

Reproduction at https://github.com/onox/yarn-esbuild-bug/tree/2d64c69b780ced693ae9889b38fe3cda1d954976 Run with `yarn install` and then `yarn build`.

I also had to add a dummy node_modules folder.

**Comment by glromeo** [comment]
Thank you @onox  for pointing me at yarn pnp... I didn't know about it and it's a nice discovery!
I am looking at your repo and I hope I can find a solution for your issue soon!

**Comment by glromeo** [comment]
I fixed the compatibility problems and now your project works fine for me, please upgrade to v1.4.3

I also added bootstrap as a dependency to your example to verify that @imports work fine

https://github.com/glromeo/esbuild-sass-plugin/blob/e1befa7a71dd7d94fca79c29a9df0c5c9eaa177f/test/fixture/pnp/src/index.js#L4

and with some little adjustmentsto esbuild-plugin-pnp... 

https://github.com/glromeo/esbuild-sass-plugin/blob/e1befa7a71dd7d94fca79c29a9df0c5c9eaa177f/test/fixture/pnp/esbuild.js#L27

it all works 🎉

**Comment by onox** [comment]
Hi, thanks, I get a `out.css` file now :+1: If I print `styles` in src/index.js then I get an empty object, but from ESBuild's documentation it appears it doesn't CSS modules yet.

Btw, you might want to remove esbuild-plugin-postcss2 in your test fixture, I only added it for @merceyz, one of the Yarn developers.
