### ISSUE TITLE
Pulls in duplicate esbuild compiler

### ISSUE THREAD

**Issue by martinpitt** [glromeo/esbuild-sass-plugin#122]
In a clean directory, running

    npm install esbuild@0.17.7 esbuild-sass-plugin@2.4.5

(Note that the latest version 2.5.0 does not work, see issue #121 )

ends up with *two* esbuild compilers:

```
❱❱❱ find -type f -name esbuild|xargs ls -lh
-rwxr-xr-x. 2 martin martin 8.6M Feb 19 12:41 ./node_modules/@esbuild/linux-x64/bin/esbuild
-rwxr-xr-x. 2 martin martin 8.3M Feb 19 12:41 ./node_modules/esbuild-linux-64/bin/esbuild
-rwxr-xr-x. 2 martin martin 8.3M Feb 19 12:41 ./node_modules/esbuild-sass-plugin/node_modules/esbuild/bin/esbuild
-rwxr-xr-x. 2 martin martin 8.6M Feb 19 12:41 ./node_modules/esbuild/bin/esbuild
```

The first and fourth, and the second and third are hardlinks (same size each, and hardlink count == 2), but these two groups are redundant. It seems esbuild-sass-plugin has a hard dependency on a specific older esbuild version:

```
❱❱❱ grep version ./node_modules/@esbuild/linux-x64/package.json ./node_modules/esbuild-linux-64/package.json 
./node_modules/@esbuild/linux-x64/package.json:  "version": "0.17.7",
./node_modules/esbuild-linux-64/package.json:  "version": "0.15.18",
```

But we really need the latest version for a bug fix.

When I install esbuild by itself, I only get one version:
```
❱❱❱ rm -rf *; npm install esbuild@0.17.7
❱❱❱ find -type f -name esbuild|xargs ls -lh
-rwxr-xr-x. 2 martin martin 8.6M Feb 19 12:45 ./node_modules/@esbuild/linux-x64/bin/esbuild
-rwxr-xr-x. 2 martin martin 8.6M Feb 19 12:45 ./node_modules/esbuild/bin/esbuild
```

Other plugins like [esbuild-plugin-copy](https://www.npmjs.com/package/esbuild-plugin-copy) don't have that problem:
```
❱❱❱ rm -rf *; npm install esbuild@0.17.7 esbuild-plugin-copy@2.0.2
❱❱❱ find -type f -name esbuild|xargs ls -lh
-rwxr-xr-x. 2 martin martin 8.6M Feb 19 12:47 ./node_modules/@esbuild/linux-x64/bin/esbuild
-rwxr-xr-x. 2 martin martin 8.6M Feb 19 12:47 ./node_modules/esbuild/bin/esbuild
```

**Comment by glromeo** [comment]
v2.6.0 should addresses this issue for good otherwise feel free to reopen this issue

**Comment by martinpitt** [comment]
Confirmed, 2.6.0 works well with esbuild 0.17.10 and avoids the duplicate. Thank you!
