### ISSUE TITLE
[FER] CSS minify for `type: css-text`

### ISSUE THREAD

**Issue by yw662** [glromeo/esbuild-sass-plugin#125]
Currently the imported CSS string is not minified and will not be minified by esbuild. It should be easy to just get a minifier sitting after sass transformer and get the string out. Is there any plan for that ?

**Comment by glromeo** [comment]
the plugin has a little misunderstood feature `transform` which allows one to post process the result of the sass compiler
it can be as simple as a function that gets the css text and minifies it and even route the content to a different loader

https://github.com/glromeo/esbuild-sass-plugin/blob/3db43583b6cb9613397ba0fb40ecaa50200d8d27/src/plugin.ts#L63-L76

**Comment by glromeo** [comment]
Here's an example of how you could do this, adapted from the [documentation](https://github.com/glromeo/esbuild-sass-plugin#--postcss)

```javascript
const postcss = require('postcss')
const postcssPresetEnv = require('postcss-preset-env')
const nano = require('cssnano')({ preset: 'default' })

esbuild.build({
  ...,
  plugins: [sassPlugin({
    async transform(source, resolveDir) {
      const {css} = await postcss([nano, postcssPresetEnv({stage: 0})]).process(source)
      return css
    }
  })]
})
```
