### ISSUE TITLE
in SSR/SST how could work?

### ISSUE THREAD

**Issue by godzzo** [glromeo/esbuild-sass-plugin#126]
Hello!

I am trying to use the plugin with React (as scssModule) to generate bundle which could run with nodejs, I am using `ReactDOMServer.renderToStaticNodeStream` to render the html.

```tsx
import styles from './Ping.module.scss';

const Ping() => (<div className={styles.hello} />);
```

I don't known If I am seeing correctly, but I don't find good option to do that, I mean the (_styleModule_) `document.head.appendChild` DOM Injection could not work with NodeJS and the (_cssTextModule_) `export default css` either won't work with `className={styles.hello}`.

So I created an own transform which collect all css text with a custom function `addSpecCss` if it is exists. Did I see it right, or miss some option which I could do that?

## Sample:

```js
const { sassPlugin, postcssModules } = require('esbuild-sass-plugin');

module.exports = {
	createPlugins: (outfile, needCssDef) => {
		const context = { needCssDef };

		return [
			sassPlugin({
				transform: specTransform(context),
			}),
		];
	},
};

const postcssModulesTransform = postcssModules({
	generateScopedName: '[name]__[local]___[hash:base64:5]',
});

const specTransform = (ctx) => async (cssText, resolveDir, filePath) => {
	const transf = postcssModulesTransform.bind(this);

	const out = await transf(cssText, resolveDir, filePath);
	const name = path.basename(filePath);

	parseTransformOut(out, name, ctx);

	return out;
};

function parseTransformOut(out, name, ctx) {
	const selectors = JSON.parse(
		out.contents
			.split('document.head')[1]
			.split('export default ')[1]
			.replace(';', '')
	);

	const css = eval(
		out.contents.replace('const css =', '').split('document.head')[0]
	);

	const cssDef = ctx.needCssDef
		? `typeof(addSpecCss) === "function" && addSpecCss(\`${css}\`);\n`
		: '';

	out.contents =
		cssDef +
		'export default ' +
		out.contents.split('document.head')[1].split('export default ')[1];
}
```

**Comment by glromeo** [comment]
since v2.9.0 css modules can be rendered into the css that esbuild bundles therefore solving this issue if I got it right...
it should be as easy as just leave the default css type. Feel free to reopen if it's not the case.

**Comment by nemosmithasf** [comment]
@glromeo I'm running into this issue as well migrating from Webpack. To clarify your suggestion, are you saying that rather than inlining, we can just attach the produced CSS?

**Comment by glromeo** [comment]
unfortunately I don't have time to re-create these sort of issues and play with them myself so my answer is purely logical...
but yes, by relying on the bundled css I don't see how you can have problems if it will be served as asset from your server

**Comment by nemosmithasf** [comment]
I see, that's somewhat sub-optimal since if we were publishing a library, it would require asking the user to import the CSS file as well.

That said, for anybody who runs into this in the future- I managed to solve my particular problem via conditional imports
