### ISSUE TITLE
`sass` should be a direct dependency, not a peer

### ISSUE THREAD

**Issue by yw662** [glromeo/esbuild-sass-plugin#127]
`esbuild-sass-plugin` requires `sass` directly and cannot work without it installed, so it should be a direct dependency.
It is not what peer dependency is for. `esbuild-sass-plugin` is a plugin of esbuild but it does not require esbuild, so this is a peer. This not the case for sass.
It would actually cause problem in real world with `pnpm` which won't install peers by default.

**Comment by glromeo** [comment]
Thank you! Fixed in v2.7.0
