### ISSUE TITLE
[FER] Suggesting new type: css-file

### ISSUE THREAD

**Issue by yw662** [glromeo/esbuild-sass-plugin#128]
I am suggesting the plugin provide a new type that would write the generated css to a css file in outDir and returns the path of the generated file.
It may have configurable hash renaming, target dir (eg. /css means all generated css should be in <outDir>/css/), or whether to preserve original directory structure (this might not be used very often since it is not how people do things today but no harm).
The import statement for such type should return full path, or configurable relative path of the file.

**Comment by glromeo** [comment]
hmm...what's the use case for this feature?
I just found a way around the limitations of CSS modules which plays nicely with
`esbuild` taking care of all CSS contents (which might have some teething issues but still
is the way to go IMHO) this feature goes the opposite way leaving those CSS contents
not processed consistently

**Comment by yw662** [comment]
This is like css-text but allow emitting standalone file instead. This is useful in cases where standalone css files are wanted, or the use do not want bundling.
Or if the style file is an "entry point", or like the stylesheets is there for other projects to import.
I know the popular taste goes the opposite where everything is encoded and bundled into a single script (except for explicit dynamic imports), and this approach is old fashioned. And anyway this can be done using css-text with a transformer. I am just suggesting because this is what this plugin can easily implement.

**Comment by glromeo** [comment]
closing as not in scope, pull requests accepted if wanted
