### ISSUE TITLE
Plugin fails when the import is an HTTP link

### ISSUE THREAD

**Issue by karl-thomas** [glromeo/esbuild-sass-plugin#13]
Howdy there, I'm trying to convert our build process to use esbuild, and working with your plugin so far has been great, but I'm having an issue where  the plugin tries to resolve links that are used as imports when `bundle: true`. [Here is a link](https://github.com/karl-thomas/sass-esbuild-repro) to a repo that I used to reproduce the error, just pull it, install, and run `node index.js` and you'll see the error. I'll also paste the error here for easy reading. We are using this to download stuff from a proprietary CDN, so i used font awesome as a placeholder, but its the same error.

```
 > sass:./src/index.scss:1:12: error: [plugin: sass-plugin] Cannot find module 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'                            
Require stack:                                                                                                                                                                                 
- /Users/kthomas/sass-esbuild-repro/node_modules/esbuild-sass-plugin/lib/plugin.js                                                                                                             
- /Users/kthomas/sass-esbuild-repro/node_modules/esbuild-sass-plugin/lib/index.js                                                                                                              
- /Users/kthomas/sass-esbuild-repro/index.js                                                                                                                                                   
      1 │ @import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css");
        ╵             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   node_modules/esbuild-sass-plugin/lib/plugin.js:172:18: note: This error came from the "onLoad" callback registered here
    172 │             build.onLoad({ filter: /^([^.]|\.\.?[^/])/, namespace: "sass" }, cached(requireResolve, transform));
        ╵                   ~~~~~~
    at setup (/Users/kthomas/sass-esbuild-repro/node_modules/esbuild-sass-plugin/lib/plugin.js:172:19)
    at handlePlugins (/Users/kthomas/sass-esbuild-repro/node_modules/esbuild/lib/main.js:736:23)
    at Object.buildOrServe (/Users/kthomas/sass-esbuild-repro/node_modules/esbuild/lib/main.js:1021:7)
    at /Users/kthomas/sass-esbuild-repro/node_modules/esbuild/lib/main.js:1745:17
    at new Promise (<anonymous>)
    at Object.build (/Users/kthomas/sass-esbuild-repro/node_modules/esbuild/lib/main.js:1744:14)
    at build (/Users/kthomas/sass-esbuild-repro/node_modules/esbuild/lib/main.js:1620:51)
    at Object.<anonymous> (/Users/kthomas/sass-esbuild-repro/index.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

In the repo i used a css file at first (the "no error" commit), same settings just without the sass plugin, and it worked fine, once I included the plugin (the "yes error" commit) it got very angry. I've tried all sorts of stuff to try and ignore the import. I tried marking it as external, using sass's `importer` option, i tried making a `esbuild` plugin to try and filter out `http` links and not doing anything to them, but I couldn't get that to work, I never got it to select the link I was looking for.  I also tried using `@use` instead of `@import`, slightly different error, `Can't find stylesheet to import` but same essence. 

So yeah, I'm kind of lost, if I can fix it with a custom plugin, cool, I will do that, I don't know how to do that but I'll try to figure it out. If you need to change something in this project, I would appreciate the assistance. I can see this being a bit of a tossup in terms of what to do, for me I would just want it to ignore it and let the browser fetch it. However, I can see an argument for fetching the external css file and concatenating it to the file on compile time. That'd slow things down, but if you're making a static site then you probably wouldn't mind.

**Comment by glromeo** [comment]
Hi Karl, I see why you're getting frustrated but don't worry I have an easy fix for you.

I released a new version of the plugin ([1.4.4](https://www.npmjs.com/package/esbuild-sass-plugin/v/1.4.4)) that accepts an ```exclude``` option which allows you let the plugin skip urls and everything flows through as it uses to do in esbuild.

I was toying with the idea of making the plugin able to resolve and bundle the CDN data but it seems that's not trivial so I won't go in that direction unless there's really a good case for it.

**Comment by karl-thomas** [comment]
That's great! I pulled it down and it worked great. As a note it did not seem to work with `@use` function, but that's not a blocker for me. And yeah, I don't have an explicit use case for bundling the downloaded files together either. Thanks for getting back to me so quickly, I appreciate it.

**Comment by cohoprints** [comment]
@karl-thomas, now that the exclude option has been deprecated, what is the recommended method for ignoring https links? I've tried adding my https imports to esbuilds external list, but continue getting import errors from the sass plugin.

**Comment by glromeo** [comment]
@cohoprints sorry Daniel, unfortunately I didn't had much time to improve the README.md for v2.x as much as I wanted
yet. 
For your case the new way is to use the `filter` option which is passed directly to esbuild that executes it directly (i.e. faster).
I think something like:
```javascript 
sassPlugin({
  filter: /^(?!https?:).*\.(s[ac]ss|css)$/
  ...
})
```
should do. 
Thank you for your patience!
