### ISSUE TITLE
Relative URL's

### ISSUE THREAD

**Issue by KiprasJ** [glromeo/esbuild-sass-plugin#133]
I cannot seem to find a solution to resolve this error bellow by using relative URL's in the project for sass files. Is there a way to handle this without changing everything to absolute paths?

```
X [ERROR] Can't find stylesheet to import.
  ╷
1 │ @import 'src/globals/global';
  │         ^^^^^^^^^^^^^^^^^^^^
  ╵
  - 1:9  root stylesheet [plugin sass-plugin]

    src/App.tsx:3:7:
      3 │ import './globals/static.scss';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~
```

The absolute path would be for this particular file: `./src/globals/global.scss`

**Comment by glromeo** [comment]
relative urls have to start with ./ otherwise they are interpreted as
modules

**Comment by glromeo** [comment]
if you have a lot of those paths implementing an import mapper
to turn src/ into ./src

**Comment by KiprasJ** [comment]
Hmm, no luck with import mapper either. Even if I manually change the path I get:

```
X [ERROR] Can't find stylesheet to import.
  ╷
1 │ @import './src/globals/global.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  - 1:9  root stylesheet [plugin sass-plugin]

    src/App.tsx:3:7:
      3 │ import './globals/static.scss';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~
```

I'm I missing something?

**Comment by glromeo** [comment]
My suggestion was generic... in the specific case of your error it looks
like you should have just "./globals" as @import

**Comment by KiprasJ** [comment]
Seems it's still the same:

```
X [ERROR] Can't find stylesheet to import.
  ╷
1 │ @import './global';
  │         ^^^^^^^^^^
  ╵
  - 1:9  root stylesheet [plugin sass-plugin]

    src/App.tsx:4:19:
      4 │ import styles from 'App.module.scss';
        ╵   
```

**Comment by KiprasJ** [comment]
Because I have not hear anything from you for a while and to make things a bit easier. I made this test repo https://github.com/KiprasJ/esbuild with the error that occurs. So I was thinking if you can use that and see what is going on? Thanks!

**Comment by glromeo** [comment]
Thank you, that's the spirit 😉
I was about to ask.
I will look into it soon

**Comment by KiprasJ** [comment]
Yeah sorry for late reply, was a little bit busy, but hopefully this will actually help you with investigation :)

**Comment by glromeo** [comment]
https://github.com/KiprasJ/esbuild/blob/b14010a3e34d08fb5efeb8568fbeb4021ef439ef/src/globals/static.scss#L1

this is where your problem is, that should be just 

```
@import 'global';
```

with that it compiles fine for me

**Comment by KiprasJ** [comment]
That resolved one issue. Thanks! Also maybe you can have a look at another case. I tried various ways as well and literally no luck:
```
X [ERROR] Can't find stylesheet to import.
  ╷
1 │ @import './src/globals/global';
  │         ^^^^^^^^^^^^^^^^^^^^^^
  ╵
  - 1:9  root stylesheet [plugin sass-plugin]

    src/components/base/text/text.tsx:1:19:
      1 │ import styles from './text.module.scss'
        ╵                    ~~~~~~~~~~~~~~~~~~~~

```

I have pushed another commit https://github.com/KiprasJ/esbuild

**Comment by glromeo** [comment]
man... you have to spend some time learning how relative paths work

**Comment by KiprasJ** [comment]
I know how it works it's just interesting how it works as it works with ```@import '../../../globals/global';``` but not for example ```'src/globals/global'``` or ```'./src/globals/global'```.
