### ISSUE TITLE
transform() signature breaks

### ISSUE THREAD

**Issue by GongT** [glromeo/esbuild-sass-plugin#134]
This commit: 6d37b2f

You changed `transform()` and breaked many things. for example:`postcssModules()`

I need `loader: "json"` in my project. like this:
```js
transform(cssText) {
	return {
		contents: JSON.stringify({ cssText, metadata }),
		loader: "json"
	};
}
```

To keep compatibility, may save `loader` value in `cssChunks`.

**Comment by glromeo** [comment]
I expect v2.8.1 to give you a solution to your problems...actually problem because at the end is just one, not many
