### ISSUE TITLE
Async rendering/sass-embedded support

### ISSUE THREAD

**Issue by wfleming** [glromeo/esbuild-sass-plugin#137]
First, thanks for the plugin! It's been very pleasant to use, and unrelated to this issue I wanted to thank you for the quick release of  #135 and the shout-out on the release for that.

For the site I'm maintaining, we build > 100 css bundles: I started using this plugin & esbuild generally by porting specific bundles from our old bundler setup, and recently took the step of mass-porting the remaining css bundles. The performance impact of this was a bit unpleasant: all the sass bundles take pretty much the same amount of time (as separate `esbuild.build` objects), and the sass bundles I was already doing in esbuild got significantly slower (from ~2s to ~9s). To be clear, this isn't that horrible for us: watch-mode rebuilds are still lightning fast for dev, and our overall wall-clock time for prod builds is still going to be way better than our old bundler setup (since even if each sass bundle is really slow at least they're all concurrent).

The usage of the synchronous sass interfaces (and the synchronous node `fs` interfaces) seemed like a pretty probable chokepoint to me. I see you had poked at some of the same ideas in your [async branch](https://github.com/glromeo/esbuild-sass-plugin/tree/async), so I suspect you've had some of the same thoughts about performance implications and I thought an issue to discuss it might be useful. I definitely understand why the current implementation uses the sync interfaces: sass's own docs say the async interface is slower (which I suspect you & I have both confirmed with our own experiments), and if you use sass's sync interface you're basically forced to also use the node fs sync interfaces in a lot of cases.

I did my own quick, messy spike of [async rendering with sass-embedded](https://github.com/wfleming/esbuild-sass-plugin/tree/render-async), and at least for my use-case it helped a lot. Smaller sass bundles are down to the several-hundred-ms range, and even our biggest bundles are only ~4.5s, well under the ~8-9s all the bundles were taking before. Getting this to a point I'd be comfortable opening a PR here is going to take a good deal more work, though, so I'm hoping to use this issue to get a sense of how useful you think this would be and the approach you think would be best.

The biggest trade-off of using `sass-embedded` seems to be it can't work on musl libc systems [due to some dart issue](https://github.com/sass/embedded-host-node/issues/143) (I had to switch the base docker image I was using for our pipeline off of alpine). "Don't support musl" feels like a deal-breaker, so I think this functionality needs to be optional or conditional on the underlying system.

If we take the "make it an option" approach, I think the easiest thing would be to just put both `sass` & `sass-embedded` as deps in package.json. On the one hand, pulling in both when any given config will only ever use one of them seems wasteful. On the other hand, `sass-embedded` isn't huge (the actual `sass-embedded` is 988k, the platform-specific linux library it pulled in for me was 8.7M), so maybe this isn't a big deal. This also keeps behavior identical for other users who don't opt-in (which is a pro for stability but possibly a con for performance).

The "conditional" approach would be using node's support for platform-specific dependencies to pull in `sass` for musl systems & `sass-embedded` for everything else, and then automatically use the appropriate one. This would effectively automatically opt-in everyone (who isn't using musl) who upgrades to a (seemingly faster) async render pipeline, but is probably a bit more work and also a bit riskier. It's unclear to me if there are cases outside of musl systems where `sass-embedded` either simply doesn't work or is in some other way incompatible/worse than `sass`, do you know of any?

Thanks for your thoughts on this!

**Comment by glromeo** [comment]
Reuse is the root of all evil 😅
I am inclined in spinning off another plugin altogether to support the
async interface.
Happy to merge efforts on it

**Comment by wfleming** [comment]
Fair enough! In that case I think my spike is pretty close to being ready to publish.

Is your preference to maintain this "other plugin" (`esbuild-sass-plugin-async`?) as a branch in this repo, or do you just want me to publish my fork as a new plugin? I certainly don't want to make any additional work for you, but also as far as I'm concerned my changes are just minor adjustments to your code, so if you want to be the owner of both variants of the plugin I want to respect that.

**Comment by glromeo** [comment]
Hi Will,

sorry for being impolite and not coming back to you earlier. I have toyed a
bit with the async branch and brought down the delays a tiny bit (see if
there's something you can pick from there) but then something else took
over... (I need to come up with an esbuild based @playwright/test asap for
my job). You read my mind, I would have named the plugin exactly the same.
I will mention it in mine soon as I have a minute to go and edit the git
readme.

Cheers!

G.

**Comment by wfleming** [comment]
Not impolite at all: I know this plugin isn't your day job, and we all get busy! Getting my spike out in some way was becoming a blocker for me with some work I had to get done, so I'm glad you don't mind I went ahead & published.
