### ISSUE TITLE
Unable to install with esbuild 0.18.0

### ISSUE THREAD

**Issue by doberkofler** [glromeo/esbuild-sass-plugin#138]
npm WARN Could not resolve dependency:
npm WARN peer esbuild@"^0.17.17" from esbuild-sass-plugin@2.9.0
npm WARN node_modules/esbuild-sass-plugin
npm WARN   esbuild-sass-plugin@"2.9.0" from the root project

**Comment by glromeo** [comment]
Unfortunately, turns out it's not just a version bump. I need time to fix the tests:
https://github.com/glromeo/esbuild-sass-plugin/pull/140

**Comment by glromeo** [comment]
This should be sorted by v2.10.0

**Comment by oalders** [comment]
Thank you, @glromeo!
