### ISSUE TITLE
How to use this plugin for build Node.js app with css modules?

### ISSUE THREAD

**Issue by krutoo** [glromeo/esbuild-sass-plugin#139]
Hi, i try to build Node.js app by esbuild with `bundle: false`.

In my app there is css modules.

In my case i receive valid JS files after build bun with imports from unexisted css modules.

They just weren't created after the build.

How can i use this plugin for build node.js app with creating `*.module.scss from `*.module.scss.js`?

**Comment by glromeo** [comment]
https://esbuild.github.io/plugins

> Plugins can also only be used with the [build](https://esbuild.github.io/api/#build) API, not with the [transform](https://esbuild.github.io/api/#transform) API.

**Comment by glromeo** [comment]
When `bundle` is false `esbuild` doesn't process the imports and as a consequence it doesn't call the plugin at all.
The only thing that I can tell is that If you don't want to bundle then you probably shouldn't use `esbuild` at all...

**Comment by krutoo** [comment]
@glromeo but esbuild allows to build application without bundling, why it not allows to run plugins in this mode?

**Comment by glromeo** [comment]
That's a bit confusing indeed.
Bear in mind that the plugin system is purely hooked into the resolve and
load steps of the life cycle of the build process.
When bundle is false the plugins are called only for the main entry point
so anything that's imported is just left as is unless you implement a
transformation of the entrypoint itself but then again this means not
really using esbuild for what it is... better off with babel or swc
