### ISSUE TITLE
It would be great if esbuild-sass-plugin would be compatible with esbuild 0.19.0

### ISSUE THREAD

**Issue by doberkofler** [glromeo/esbuild-sass-plugin#142]
npm WARN Found: esbuild@0.18.20
npm WARN node_modules/esbuild
npm WARN   dev esbuild@"0.19.0" from the root project
npm WARN   2 more (bundle-require, esbuild-sass-plugin)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer esbuild@"^0.18.0" from esbuild-sass-plugin@2.10.0
npm WARN node_modules/esbuild-sass-plugin
npm WARN   dev esbuild-sass-plugin@"2.10.0" from the root project

**Comment by glromeo** [comment]
v2.11.0 should freshen things up a bit!

**Comment by doberkofler** [comment]
v2.11.0 still depends on esbuild ^0.18.0, so I'm not sure how this SR is fixed?

**Comment by glromeo** [comment]
doh!
I made a typo... thank you

**Comment by glromeo** [comment]
v2.12.0 is the charm
