### ISSUE TITLE
postcss Unocss inoperative

### ISSUE THREAD

**Issue by zhangchenna** [glromeo/esbuild-sass-plugin#150]

**Comment by zhangchenna** [comment]
import esbuild from 'esbuild';
import { sassPlugin } from 'esbuild-sass-plugin';
import postcss from 'postcss';
import postcssUnocss from '@unocss/postcss';

 sassPlugin({
        async transform(source) {
          const { css } = await postcss([
            ...postcssPlugins,
            postcssUnocss({
              content: ['src/**/*.{js,ts,jsx,tsx,vue}'],
            }),
          ]).process(source);
          return css;
        },
      }),


// unocss Not transferred correctly
@unocss;.qt-button-group{width:100%;background-color:#fff}

**Comment by glromeo** [comment]
I am sorry but I can't look into 3rd party postcss plugin issues... unless, have you checked what is returned in css ?
just a console log before the return css is enough to see whether your call to postcss yields the results you expect.
I guess if there's an issue is with the call to post css...in any case this is beyond the scope of this plugin
