### ISSUE TITLE
When "type" is "style" esbuild ignores url-imported files

### ISSUE THREAD

**Issue by aak-lear** [glromeo/esbuild-sass-plugin#151]
I'm trying to bundle all files to single JavaScript file.

When I place `{ type: 'style' }` to sass-plugin config, esbuild ignores all `url(...)` imports in style-files and leaves them unchanged.
This setting also affects pure css-files, which I import directly from js.

You can see example here: https://github.com/aak-lear/esbuild-with-sass-plugin-example

Just run `npm i` and `npm run build`. In the `dist` folder will be single javascript file with styles, that I import in the `app.tsx`. But woff-file  imported with `url(...)` didn't get into the bundle.

If you remove `type: 'style'` in plugin config, then esbuild will bundle all css to separate file and resolve imported woff-file

**Comment by glromeo** [comment]
please read carefully the type section in the README
https://github.com/glromeo/esbuild-sass-plugin#type
this has already been discussed here
https://github.com/glromeo/esbuild-sass-plugin/issues/92#issuecomment-1219209442
