### ISSUE TITLE
How to handle relative `url` paths in 3rd party packages

### ISSUE THREAD

**Issue by DEfusion** [glromeo/esbuild-sass-plugin#153]
In some of our 3rd party packages there are things like:

```
background-image: url(images/foo.png);
```

After digging around the docs and older issues this is what I came up with, but is it correct or am I missing something? Also I know this could be tightened up into a single regexp and replace, I'm just leaving it like this to help debug as we try out migrating from webpack to esbuild.

```
 precompile(source, pathname) {
    const basedir = path.dirname(pathname);
    const reg = /url\(["']?([^('"\))]+)["']?\)/g;

    (source.match(reg) || []).forEach((match) => {
      const url = match.replace(reg, "$1");
      if (url.match(/^(http|@|data|#)/)) return;

      source = source.replace(match, `url(${basedir}/${url})`);
    });
    return source;
  }
```

If you want a real world example then see https://github.com/Leaflet/Leaflet/blob/main/dist/leaflet.css#L318

If I simply import `'leaflet/dist/leaflet';` I get `✘ [ERROR] Could not resolve "images/layers.png"` etc.

**Comment by glromeo** [comment]
sorry for the late reply...I've been quite busy lately

given

#### /testproject/package.json
```
{
	"dependencies": {
		"esbuild": "^0.19.2",
		"esbuild-sass-plugin": "^2.13.0",
		"leaflet": "^1.9.4"
	}
}
```

#### /testproject/src/index.js
```
import styles from 'leaflet/dist/leaflet.css'
```

#### /testproject/build.mjs
```
import * as esbuild from 'esbuild';
import { sassPlugin } from 'esbuild-sass-plugin';
import path from 'node:path';

await esbuild.build({
  entryPoints: ['./src/index.js'],
  outdir: 'dist',
  bundle: true,
  loader: {
    '.png': 'file',
  },
  plugins: [
    sassPlugin({
      precompile(source, pathname) {
        const basedir = path.dirname(pathname);
        const reg = /url\(["']?([^('"\))]+)["']?\)/g;

        (source.match(reg) || []).forEach((match) => {
          const url = match.replace(reg, "$1");
          if (url.match(/^(http|@|data|#)/)) return;

          source = source.replace(match, `url(${basedir}/${url})`);
        });
        return source;
      },
    }),
  ],
});

```

It works just as expected... on windows that has to be said but I don't see how that would affect this issue
If this doesn't help you have to reproduce the issue in a project and we can take it from there

**Comment by DEfusion** [comment]
So it's expected that I need to rewrite the URLs via `precompile` like this in order for the imports to work. I was just checking that I wasn't missing something here.

Thanks for your response.
