### ISSUE TITLE
postcssPresetEnv debug being captured/surpressed?

### ISSUE THREAD

**Issue by DEfusion** [glromeo/esbuild-sass-plugin#154]
I _think_ that it is this plugin that's causing this, but also I might be wrong.

With the following:

```
async transform(source) {
          const { css } = await postcss([
            autoprefixer,
            postcssPresetEnv({ debug: true, stage: 0 })
          ]).process(source, { from: undefined });
          return css;
        },
```

I would expect to get the post css debug logged but I don't, I have tried changing the `logLevel` (currently at `info`) but doesn't seem to make a difference.

**Comment by glromeo** [comment]
https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env#debug

the output goes to stdout and the plugin is not messing with stdout 

could this help maybe? https://github.com/evanw/esbuild/issues/1869

**Comment by DEfusion** [comment]
Thanks for pointing me at the esbuild issue.
