### ISSUE TITLE
the src folder maybe needed in published package

### ISSUE THREAD

**Issue by hsiaosiyuan0** [glromeo/esbuild-sass-plugin#155]
hi, thanks for this nice package, I find that the src folder does not exists in the published package which will cause the sourcemap cannot work as they're expected

can we add src folder into the `files` field [here](https://github.com/glromeo/esbuild-sass-plugin/blob/ffb21de51f74c2cc4aa4025b0a0cb3ae520821b3/package.json#L15)

**Comment by glromeo** [comment]
Thank you for your contribution and sorry for the late reply... I was hesitant to add src to the package but I reckon is not a bad idea. Merged and shipped in v2.16.1
