### ISSUE TITLE
`ERROR` Can't find stylesheet to import when I have `@use` in my `scss` files

### ISSUE THREAD

**Issue by mahbubme** [glromeo/esbuild-sass-plugin#157]
TBH I am new in esbuild area and tried to move my current webpack configuration to esbuild. Here is my esbuild configuration file. 

```import * as esbuild from 'esbuild'
import {sassPlugin} from 'esbuild-sass-plugin'
import path from 'path'
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

await esbuild.build({
    entryPoints: [
        { out: 'frontend', in: './resources/ts/frontend/index.ts'},
        { out: 'block-editor', in: './resources/ts/block-editor/index.ts'},
        { out: 'global', in: './resources/ts/global/index.ts'},
    ],
    bundle: true,
    minify: true,
    outdir: 'assets',
    plugins: [
        sassPlugin(),
    ],
}).catch(() => process.exit(1));
```

So when running `npm run build` I am getting the following errors pointing that unable to find the stylesheet to import. 

<img width="782" alt="Screenshot 2023-12-19 at 23 48 57" src="https://github.com/glromeo/esbuild-sass-plugin/assets/10685760/b1b1d1cb-37ba-4c54-a448-0166f840e3bc">

Any ideas how can I fix the issue?

**Comment by anitagraham** [comment]
I have been successfully using `@use` in my `SCSS` files with this plugin for a couple of months.
However, on the way I did note #136 where using `@` in the paths was causing an error. 
Perhaps use a different path prefix?  #136 has a  good description and response to this problem.

I am just revisiting the issue as  I have changed my path structure and need to rewrite my importmapper.
