### ISSUE TITLE
npm warning when upgrading to esbuild 0.20.0

### ISSUE THREAD

**Issue by doberkofler** [glromeo/esbuild-sass-plugin#161]
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: esbuild@0.19.12
npm WARN node_modules/esbuild
npm WARN   dev esbuild@"0.20.0" from the root project
npm WARN   3 more (bundle-require, esbuild-sass-plugin, tsx)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer esbuild@"^0.19.4" from esbuild-sass-plugin@2.16.1
npm WARN node_modules/esbuild-sass-plugin
npm WARN   dev esbuild-sass-plugin@"2.16.1" from the root project

**Comment by glromeo** [comment]
v3 has been upgraded to esbuild 0.20 😉

**Comment by davidkarlsson** [comment]
Thank you @glromeo!
