### ISSUE TITLE
sass-embedded is not supported on all platforms

### ISSUE THREAD

**Issue by jelly** [glromeo/esbuild-sass-plugin#168]
Since 3.0.0 this plugin switched to sass-embedded it now relies on binaries to be available for all platforms. We also build for s390x and aarch64 (and likely ppc64) for which sass-embedded does not distribute binaries.

Would it be possible to maybe allow for either `sass` or `sass-embedded` to be a dependency of esbuild-sass-plugin. Looking at [sass-loader](https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L61) and [vite](https://github.com/vitejs/vite/issues/6734). This seems to be something npm can support.

I'm happy to write a patch to make this happen.

**Comment by glromeo** [comment]
I am looking into trying and providing both sass as default to work on any platform and leave sass-embedded as an option
...thank you for spotting this shortcoming! It sucks indeed

**Comment by glromeo** [comment]
please let me know how it goes with v3.1.0

**Comment by martinpitt** [comment]
@glromeo Thanks a lot! It works very well indeed, ARM builds are happy again.
