### ISSUE TITLE
Builds with `embedded: true` hang forever on Cloudflare Pages worker

### ISSUE THREAD

**Issue by jackyzha0** [glromeo/esbuild-sass-plugin#174]
Really strange because Cloudflare Pages purportedly uses Ubuntu 22.04 which _should_ be a supported platform for `sass-embedded`

**Comment by glromeo** [comment]
I can't help unless you point me to an issues with the code of the plugin.
Please figure out if and where this is an issue with the plugin 
I suggest starting with making sure that outside of the plugin 
sass-embedded works fine in Cloudflare
