### ISSUE TITLE
Add support for latest esbuild version 0.21.0

### ISSUE THREAD

**Issue by doberkofler** [glromeo/esbuild-sass-plugin#176]

**Comment by davidkarlsson** [comment]
The latest verrsion of esbuild is [v0.21.2](https://github.com/evanw/esbuild/releases/tag/v0.21.2) now which seems to work great with esbuild-sass-plugin in spite of the peer dependency warning.

**Comment by doberkofler** [comment]
It would really help if this could be fixed ;-)

**Comment by glromeo** [comment]
released with v3.3.0... apologies for the delay in merging this
