### ISSUE TITLE
Feature request: generate `*.map` files instead of inlining source maps

### ISSUE THREAD

**Issue by tliu30** [glromeo/esbuild-sass-plugin#180]
Hi `esbuild-sass-plugin` team,

Would it be possible to add a feature allowing us to generate `*.map` files instead of inlining the source maps?

The motivation is that inlining the source maps makes it so that builds don't reproduce across different computers when you use the "minify: true" option in `esbuild`. This happens because of the following chain of events:
- different computers => different filesystems
- different filesystems => different "sourceRoot" in the generated source maps
- different generated source maps => different inlined source mapping urls
- different inlined source mapping urls => different character frequencies, leading to differences in the files generated by esbuild's minification algorithm

This isn't a problem with `*.map` files because those can be the same across different filesystems (in particular, when generated with relative urls, e.g., `sourceMappingURL=types.js.map`).

I'm not sure how difficult this would be to do - would also be open to taking a look at adding this feature myself, if the maintaining team would be open to that.

Sincerely,
Tony

**Comment by glromeo** [comment]
The sourcemap files creation is governed by esbuild. As a plugin implementor one has not control over the generation of sidecar files of any sort and somehow the whole target FS structure is kind of hidden.
I suggest you look into esbuild docs to see if you can tailor the output to your needs and as far as this plugin is concerned
the sourcemapping is of little use really unless you aim at collecting CSS coverage
Please have a little look yourself at the code I hope I haven't misunderstood your ask
https://github.com/glromeo/esbuild-sass-plugin/blob/f0e58c9a4a24e249c6da3bcf7e8c769b74eb7ac4/src/render.ts#L190
