### ISSUE TITLE
Relative Url Rewriting

### ISSUE THREAD

**Issue by GravlLift** [glromeo/esbuild-sass-plugin#19]
[Sass doesn't like relative urls in non-entry files.](https://github.com/bholloway/resolve-url-loader/tree/v4-maintenance/packages/resolve-url-loader#whats-the-problem-with-sass) Webpack gets around this shortcoming with the [resolve-url-loader plugin](https://github.com/bholloway/resolve-url-loader), which [uses sourcemaps generated by Sass to rewrite the urls after the compilation has completed](https://github.com/bholloway/resolve-url-loader/blob/v4-maintenance/packages/resolve-url-loader/docs/how-it-works.md).

Esbuild doesn't yet [output sourcemaps into the build output](https://github.com/evanw/esbuild/issues/519) proper, but this plugin could still have access to them by adding a sourcemap option to the sass call and then saving [the map property that's returned](https://sass-lang.com/documentation/js-api#result-map). With those maps in memory, similar relative url rewriting could be achieved.

**Comment by glromeo** [comment]
Sorry @GravlLift but what you ask for is a feature I don't intend to implement. 
If there's an issue for a developer that is conceptually not in esbuild+sass but rather in sass itself.
I understand that having a single sass entry file can be more efficient or if you prefer more in line with the mindset of a web designer but it's not within the scope of this plugin. 
For the workflows I am keen to support modularising/scoping the sass code is better done by using javascript imports (with one sass entry-file per component) and by limiting the usage of sass imports to shared styles & macros.
