### ISSUE TITLE
Support for new math.div Sass module

### ISSUE THREAD

**Issue by Canuckaholic** [glromeo/esbuild-sass-plugin#21]
I have some SCSS that uses "/" to perform a division operation, but this produces a deprecation warning:

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
```

If I change this to use "math.div" I get the following error:

```
error: [plugin: sass-plugin] There is no module with the namespace "math"
```

Suggestions?

**Comment by ArthurHeitmann** [comment]
I'm using `"sass": "^1.37.5"` and `math.div` works for me. Maybe try updating sass?

**Comment by glromeo** [comment]
@Canuckaholic please update to v1.4.10
