### ISSUE TITLE
NoSuchMethodError: method not found: 'get$iterator'

### ISSUE THREAD

**Issue by gregorypratt** [glromeo/esbuild-sass-plugin#24]
When I run my esbuild command using the below config I receive the following error everywhere scss files are imported:

```
 > src/init.ts:1:7: error: [plugin: sass-plugin] NoSuchMethodError: method not found: 'get$iterator' (J.getInterceptor$ax(...).get$iterator is not a function)
    1 │ import "./index.scss";
```

I'm new to esbuild so apologies if it's not setup correctly but I'm stuck as to how to solve this?

**esbuild.js:**

```js
import path, { dirname } from "path";
import { fileURLToPath } from "url";

import { build } from "esbuild";
import { ScssModulesPlugin as scssModulesPlugin } from "esbuild-scss-modules-plugin";
import { sassPlugin } from "esbuild-sass-plugin";
import svgPlugin from "esbuild-plugin-svg";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const scssModulesPluginCache = new Map();

build({
  entryPoints: ["./src/index.js"],
  outdir: "build/",
  bundle: true,
  minify: true,
  target: ["es2020"],
  loader: {
    ".js": "jsx",
    ".png": "file"
  },
  plugins: [
    scssModulesPlugin({
      cache: scssModulesPluginCache,
      scssOptions: {
        sourceMap: true,
        includePaths: path.resolve(__dirname, "node_modules")
      },
      generateScopedName: "[name]__[local]___[hash:base64:5]"
    }),
    sassPlugin({ includePaths: path.resolve(__dirname, "node_modules") }),
    svgPlugin()
  ]
}).catch(() => process.exit(1));

```

**Comment by glromeo** [comment]
No worries, the problem is just that [includePaths is an array](https://sass-lang.com/documentation/js-api#includepaths)!
Change it to:

```includePaths: [path.resolve(__dirname, "node_modules")]```

otherwise your setup is ok

**Comment by glromeo** [comment]
@gregorypratt I couldn't help noticing that you are trying to use my plugin together with scssModulesPlugin and I don't know whether that mix is really going to work for you. It was long time I wanted to add css modules to my plugin too and this has been the occasion for me to get a move on and add that feature.

I invite you to try and look [here](https://github.com/glromeo/esbuild-sass-plugin/tree/main/test/fixture/css-modules) for an example of how simple it is to get css modules with just **esbuild-sass-plugin**

I hope this helps!
