### ISSUE TITLE
why `require.resolve` is set to cwd ?

### ISSUE THREAD

**Issue by visamz** [glromeo/esbuild-sass-plugin#25]
https://github.com/glromeo/esbuild-sass-plugin/blob/ccfa67a1ffcbbf0bc117b19a239e457e469c280e/lib/utils.js#L6

when my esbuild cli was installed in global，and also installed node-sass, then get:
```
Cannot find module 'node-sass', make sure it's installed. e.g. yarn add -D node-sass Error: Cannot find module 'node-sass'
```
But, i don't want to install  'node-sass' in my   project directory, because it only need in building time and has nothing to do with the project business.

**Comment by glromeo** [comment]
@visamz I would suggest you to use dev dependencies instead of global for development tools in  order to keep your project neatly self contained.

Nevertheless I see I made a mistake assuming resolve would fall back to global modules if it can’t find them locally and I want to look into fixing that without requiring the users to fiddle with environment variables, links or other annoying shaman rituals!

**Comment by glromeo** [comment]
@visamz please update to v1.5.1. From that version `includePaths` will be used by **require.resolve** and you can get your build to work like explained in the examples provided in the [test/issues/25 folder](https://github.com/glromeo/esbuild-sass-plugin/tree/main/test/issues/25)

**Comment by visamz** [comment]
Thanks.

er, maybe i said was not clear....

I am making cli tool for my team with  esbuild, it can be installed in global.  The tool contain node-sass,  be installed in dev dependencies at cli tool dir, but not in bussiness dir.

That means, cli tool dir is not bussiness project dir, node-sass was not installed in global. Of course , node-sass  may also be installed globally.

I think,  esbuild-sass-plugin would auto find node-sass or other pakcage in recusive path，which is better than set only one includePath. What do you think ？

**Comment by visamz** [comment]
I think be better like this:

```js
try {
    return require(module)
} catch (e) { }

try {
    return require(require.resolve(module, includePaths ? { paths: includePaths } : { paths: [process.cwd()] }));
}
catch (e) {
    console.error(`Cannot find module '${module}', make sure it's installed. e.g. yarn add -D ${module}`, e);
    process.exit(1);
}
```

**Comment by glromeo** [comment]
Admittedly I am a bit confused by your explanation but I understand what you want to do with your code example.

You will find the change in v1.5.2... 

https://github.com/glromeo/esbuild-sass-plugin/blob/9759a6ff4b698acd7126b7237a10ff549b43389b/src/utils.ts#L6-L17

**NOTE**: Finding a co-located tool is an exception not the rule

I hope this helps, please let me know if it does!

**Comment by visamz** [comment]
@glromeo That's worked,  thinks.
