### ISSUE TITLE
Question: is there some way to remain the path in `url()` as is?

### ISSUE THREAD

**Issue by idlist** [glromeo/esbuild-sass-plugin#29]
For example, I currently have something like:

```sass
@font-face
  font-family: 'Open Sans'
  src: url('/public/open-sans.woff2')
```

And the `url` here is the path directly to where the font file would be in the output directory (since I would manually copy the `public` folder to the output directory) instead of where the source of the font is. 

Currently, with `bundle: true` (i.e. I want to bundle the `.sass` files), The only way I have figured out to make this piece of code work is to change the `url` path to the source of the font, and set `loader: { '.woff2': 'file' }` or `loader: { '.woff2': 'dataurl' }` to esbuild. But both of the settings are not really meet my need, since with the both loaders the font file is copied twice, one manually and one by esbuild, and with `file` the filename is renamed and the `url` is remapped.  On the other hand, not setting the loader would throw the error of `Could not resolve "/public/open-sans.woff2"`, and settings `exclude: \.woff2$\` in this plugin cannot solve this error. 

What I want to achieve is to make the path inside `url('/public/open-sans.woff2')` remains as is after the bundling. I would appreciate if someone could give me some advice.

**Comment by glromeo** [comment]
I would suggest you look at the [`external` option of esbuild](https://esbuild.github.io/api/#external) or try something like this:

```javascript
esbuild.build({
  plugins: [{
    name: "custom-resolver",
    setup(build) {
      build.onResolve({filter: /public\/.*woff2$/}, ({path}) => {
        return {path, external: true, namespace: "provided"};
      });
    }
  },   
  sassPlugin({...}),
  ...
  ],
  ...
})
```

**Comment by glromeo** [comment]
I tried this in your project and it works for me:

![image](https://user-images.githubusercontent.com/160981/135941751-7d442707-524b-4330-8e20-889ce1afcc00.png)

**Comment by idlist** [comment]
Thanks!

I have found the main point is that the path in the `external` option should be corresponding to the one in `url` in the Sass file. 

For example, if `external: ['public/*']`, then `url('public/*')` would be excluded by esbuild, and if I want to exclude `url('/public/*')`, then I should set `external: ['/public/*']` in esbuild.
