### ISSUE TITLE
why not set a resolve directory when the type is "css"?

### ISSUE THREAD

**Issue by FailLone** [glromeo/esbuild-sass-plugin#3]
I got this error when using the plugin:
![image](https://user-images.githubusercontent.com/11540557/110734180-3a36ae00-8262-11eb-8018-0351e11e3d19.png)

but, in your code, this looks like intentional:
```js
function transform(path, type) {
      let contents = path.endsWith(".css") ? fs_1.readFileSync(path, "utf-8") : renderSync(path);
      return type === "css" ? {
          contents: contents,
          loader: "css",
      } : {
          contents: makeModule(contents, type),
          loader: "js",
          resolveDir: path_1.dirname(path)
      };
  }
```
so, why not set a resolve directory when the type is "css"? and how to resolve this problem?

**Comment by glromeo** [comment]
Thank you for using the plugin, admittedly that was just inattention. Please update to 1.0.10.
