### ISSUE TITLE
esbuild loader for woff2 being ignored

### ISSUE THREAD

**Issue by Rassell** [glromeo/esbuild-sass-plugin#35]
Hi,

First of all thanks for this awesome plugin!

I have a (minor?) issue with it (or maybe I'm just doing something wrong). I'm being ignored trying to use a custom font...

my code (not all code copied so is easier to follow):

Header.tsx:
```
import styles from './Header.module.scss';

export function Header() {
```

Header.module.scss:
```
@import '../../../styles/main.scss';

.desktopHeader {
      font-family: 'Font-Italic';
 ```
 
main.scss:
```
@import './color-pallete.scss';
@import './theme.scss';
@import './fonts.scss';
```

fonts.scss:
```
@font-face {
    font-family: 'Font-Italic';
    font-style: normal;
    font-weight: 400;
    src: url('../assets/fonts/Pro/Pro-Italic.woff2') format('woff2');
}
```

esbuild:
```
const { build } = require('esbuild');
const { sassPlugin, postcssModules } = require('esbuild-sass-plugin');
const { dtsPlugin } = require('esbuild-plugin-d.ts');

build({
  bundle: true,
  sourcemap: true,
  minify: true,
  splitting: true,
  format: 'esm',
  target: ['esnext'],
  entryPoints: ['src/Header.tsx'],
  outdir: 'dist/',
  loader: {
    '.woff': 'dataurl',
    '.woff2': 'dataurl',
  },
  plugins: [
    sassPlugin({
      type: 'css-text',
      transform: postcssModules({}),
    }),
    dtsPlugin(),
  ],
}).catch(e => console.error(e.message));
```

i have tried diferent loaders with no luck...

many thanks in advance

**Comment by glromeo** [comment]
One is happy in being of service! 😄 
One thing I noticed is that you specify `font-family: 'Font-Italic';` in `@font-face` but then you use `font-family: 'Lidl-Font-Italic';` in `Header.module.scss`...could that be it?
Do you have any errors in the build log?
