### ISSUE TITLE
Missing Default Export

### ISSUE THREAD

**Issue by iChip** [glromeo/esbuild-sass-plugin#46]
This plugin isn't currently interoperable with an executor like e.g. https://github.com/sevenwestmedia-labs/nx-plugins/blob/main/libs/nx-esbuild/src/executors/build/executor.ts#L44 because it doesn't include a default export (the plugin).

I do think it's desirable for the default export of a plugin package to be the plugin.

**Comment by glromeo** [comment]
I see why it's useful in that case... I'll add it!

**Comment by glromeo** [comment]
Added in v1.8.0
