### ISSUE TITLE
Can't find stylesheet to import

### ISSUE THREAD

**Issue by joeworkman** [glromeo/esbuild-sass-plugin#52]
I have looked at similar issues filed about this but was unable to find a solution. I also tried the 2.0-alpha version. 

If you clone this repo: https://github.com/foundation/proton-sites-template

After you install, run a `yarn build`. You will see that it fails trying to load a Sass library. Here is a snippet from the esbuild script.

```
await esbuild.build({
       ...
        plugins     : [
            sassPlugin({includePaths: [
                "node_modules/foundation-sites/scss/",
                "node_modules/motion-ui/src/",
            ]}),
        ],
    }).catch(() => process.exit(1));
```

If I run `sass` directly from the CLI. It works like a charm. 

```
$ sass -I node_modules/foundation-sites/scss -I node_modules/motion-ui/src src/styles/site.scss output.css
```

**Comment by glromeo** [comment]
I will try your repo against v2.x to be sure it works, please leave this issue open until then. 

Module resolution is really in **alpha** stage in there and I have bigger fish to fry so I suggest 
you to try and use [sass-extended-importer](https://github.com/wessberg/sass-extended-importer)
with v1.x:

```javascript
const {createImporter} = require("sass-extended-importer");

await esbuild.build({
  ...
  plugins: [
    sassPlugin({
      includePaths: [
        "node_modules/foundation-sites/scss/",
        "node_modules/motion-ui/src/",
      ], 
      importer: createImporter()
    }),
  ],
}).catch(() => process.exit(1));
```

please note that sass-extended-importer can't work with v2.x

**Comment by joeworkman** [comment]
@glromeo Dude! I swear that I tried that so many different ways. Thank you so much. You may want to add that exact example into the README. Could be helpful for others. 

My build works now. I am happy to help test v2 if you get that working.

**Comment by joeworkman** [comment]
Should I expect this to work with `watch:true` enabled? It does not see to pick up changes.

**Comment by glromeo** [comment]
watch mode should work regardless of the importer being used, if you definitely see an issue create a repo that reproduce it and I can look into it
