### ISSUE TITLE
Support nodeLinker pnp

### ISSUE THREAD

**Issue by navidemad** [glromeo/esbuild-sass-plugin#53]
Hello,

I was taking in consideration to move from yarn nodeLinker with node_modules to the pnp version, and I was wondering have you take a look on how this awesome plugin you created could reach packages with this new way ?

I know there is @yarnpkg/esbuild-plugin-pnp and it works perfectly for my javascript assets but when it comes to compile my stylesheets trouble are coming my way.

If you have any ideas or questions, let me know

**Comment by glromeo** [comment]
Thank you @navidemad, there's an example of using the plugin with pnp in https://github.com/glromeo/esbuild-sass-plugin/tree/main/test/fixture/pnp. My focus is right now is on releasing v2.x, when that's out if there are issues using it with pnp we can take it from there
