### ISSUE TITLE
README precompile example path separator issue

### ISSUE THREAD

**Issue by GravlLift** [glromeo/esbuild-sass-plugin#58]
There's something strange going on with path separators on Windows in the [precompile example in the readme](https://github.com/glromeo/esbuild-sass-plugin/blob/5cc582c281364e7021c5adf187cd71054ebbf055/README.md?plain=1#L170). The `path.dirname` call correctly reads out the base directory as, for example, `C:\\folder\\subFolder`, and the path is successfully combined with the item in the `url` call, generating something like `C:\\folder\\subFolder/./assets/image/png`.

If I add a dummy plugin to esbuild, I can see that an onResolve call will then be attempted to be made to `C:foldersubFolder/./assets/image/png` by this plugin.

I was able to resolve the issue by either double escaping the windows path seperator...
```ts
return source.replace(
  /(url\(['"]?)(\.\.?\/)([^'")]+['"]?\))/g,
  `$1${baseDir.replace(/\\/g, '\\\\')}/$2$3`
);
```

... or by using `/` instead:
```ts
return source.replace(
  /(url\(['"]?)(\.\.?\/)([^'")]+['"]?\))/g,
  `$1${baseDir.replace(/\\/g, '/')}/$2$3`
);
```

I'm not exactly sure what's going on there, but at least its workaroundable.

**Comment by glromeo** [comment]
I close this hoping the documentation is clear enough now
