### ISSUE TITLE
v2.0.2 on npm build missing lib folder

### ISSUE THREAD

**Issue by kavika-1** [glromeo/esbuild-sass-plugin#59]
For some reason `2.0.2` on `npm` doesn't seem to contain the lib folder, so our builds are failing
![image](https://user-images.githubusercontent.com/7366181/148659481-63dacefa-371c-4cae-8c99-2279e5a9895a.png)

For reference, `2.0.1` does:
![image](https://user-images.githubusercontent.com/7366181/148659496-9a8748b8-5433-4fcd-a661-7545b28b4990.png)

Workaround for now is install `2.0.1`

**Comment by glromeo** [comment]
@kavika-1 my sincere apologies for the mistake...I just introduced the github action and I didn't realize it was missing the build step!

**Comment by glromeo** [comment]
please update to https://www.npmjs.com/package/esbuild-sass-plugin/v/2.0.3

**Comment by kavika-1** [comment]
confirmed working - thanks for the great library
