### ISSUE TITLE
Imports from node_modules

### ISSUE THREAD

**Issue by 58bits** [glromeo/esbuild-sass-plugin#6]
I'm trying to use the material-components-web package https://github.com/material-components/material-components-web. 

I can create node_modules specific imports like - `@use "../../../node_modules/@material/theme"` - but within the material components themselves, there are additional `@forward`, `@use`, `@import` statements that will not resolve.

Ideally I'd like to be able to use

```
@use "@material/theme" with (
  $primary: white,
  $secondary: #285c86,
  $on-primary: white,
  $on-secondary: white,
  $background: #17243b,
  $surface: #17243bc7,
);
```
 or
```
@use '@material/button/mdc-button';
```

Is there a way to support sass components from node_modules like this? Or is this an esbuild issue? There is a similar issue here, with a suggested solution - https://github.com/koluch/esbuild-plugin-sass/issues/15

**Comment by glromeo** [comment]
HI @58bits  my plugin already uses resolve for sass imports
https://github.com/glromeo/esbuild-sass-plugin/blob/43737116a7d4fb2360b3d9eedc39ad9e249bba55/lib/plugin.js#L74-L77
but it might be that your layout doesn't work with require defaults... try and pass an `includePaths` that points to your node_modules, something like this: 
https://github.com/glromeo/esbuild-sass-plugin/blob/43737116a7d4fb2360b3d9eedc39ad9e249bba55/test/esbuild-sass-plugin.test.ts#L91-L94

**Comment by 58bits** [comment]
Hi @glromeo  - thanks very much for taking the time to reply. I've tried updating sassPlugin settings as you've described above, but I'm still getting `error: [sass-plugin] Can't find stylesheet to import`

I'm new to esbuild, and so it's highly likely I've  setup something incorrectly.

I've create a test repo here... https://github.com/58bits/esbuild-test 

Can you see anything obviously wrong with this?

**Comment by 58bits** [comment]
Hi - I've updated the test repo at https://github.com/58bits/esbuild-test

I've fixed up all @use statements, and changed the build directory and project structure. I'm also using the `~` syntax to specific material modules - and this works, but then there are sub modules, or dependencies that fail.  

I'm only attempting to import one component - via `src/styles/components/_year-select.scss`

And I'm getting the following error:

```
 > src/index.js:1:7: error: [sass-plugin] Can't find stylesheet to import.
   ╷
23 │ @use '@material/feature-targeting/feature-targeting';
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@material/select/_select-helper-text-theme.scss 23:1  @forward
  node_modules/@material/select/_index.scss 23:1                     @use
  src/styles/components/_year-select.scss 2:1                        @use
  src/styles/style.scss 3:1                                          root stylesheet
      1 │ import './styles/style.scss'
```

**Comment by glromeo** [comment]
@58bits 

According to https://github.com/material-components/material-components-web/tree/master/packages/mdc-select
you have to change your `_year-select.scss` to:

```
@use "../config/config" as *;

@use "~@material/list/mdc-list";
@use "~@material/menu-surface/mdc-menu-surface";
@use "~@material/menu/mdc-menu";
@use "~@material/select/styles";
@use '~@material/select';

.mdc-select--filled:not(.mdc-select--disabled) .mdc-select__anchor {
  background-color: $dashboard-panel-background-color;
}
...
```

then in `build.js` just use this setup for esbuild-sass-plugin:

```
  plugins: [sassPlugin({
    type: "style", 
    includePaths: [
      path.resolve(__dirname, "node_modules"),
    ] 
  })],
```
