### ISSUE TITLE
How do I filter module and global CSS and SCSS files?

### ISSUE THREAD

**Issue by rodoabad** [glromeo/esbuild-sass-plugin#60]
```js
plugins: [
  // do module.scss/css first
  sassPlugin({
    filter: /.module.(s[ac]ss|css)$/,
    type: 'style',
    transform: postcssModules({
        // ...put here the options for postcss-modules: https://github.com/madyankin/postcss-modules
    })
  }),
  // do scss/css second
  sassPlugin({
    filter: /.(s[ac]ss|css)$/,
    type: 'style'
  })
];
```

This is what I'm doing right now we have the following files.

- foo.css // global
- bar.scss // global
- foo.module.css // local CSS module
- bar.module.scss // local CSS module

**Comment by glromeo** [comment]
yes @rodoabad that's the intended usage... did you run in any issues?

*NOTE* you can simply use `.s?css$` in your cases by the way

**Comment by rodoabad** [comment]
@glromeo one of the problems that I have is, if ever the order is switched, then it's going to give an error.

```js
        plugins: [
            sassPlugin({
                filter: /.s?css$/,
                type: 'style'
            }),
            sassPlugin({
                filter: /.module.s?css$/,
                type: 'style',
                transform: postcssModules({})
            }),
        ],
```

```bash
✘ [ERROR] No matching export in "sass-plugin-0:/Users/Development/component-library/esm/foo.module.scss" for import "default"

    esm/index.tsx:3:7:
      3 │ import styles from './foo.module.scss';
        ╵        ~~~~~~

✘ [ERROR] No matching export in "sass-plugin-0:/Users/Development/component-library/esm/bar.module.css" for import "default"

    esm/index.tsx:4:7:
      4 │ import css from './bar.module.css';
        ╵        ~~~
```

**Comment by glromeo** [comment]
yes that's intentional, `esbuild` checks the plugins in the order they are listed by testing the [`filter`](https://esbuild.github.io/plugins/#filters) regexp so the plugin with the most specific regexp (the module one in your case) has to come before the one with the less specific regexp.

**Comment by rodoabad** [comment]
Thanks, for clearing that up. Looks like I have to specific.

```js
            sassPlugin({
                filter: /.module.s?css$/,
                type: 'style',
                transform: postcssModules({})
            }),
            sassPlugin({
                filter: /^(?!.*.module.scss$).*.scss$/,
                type: 'style'
            }),
```

Just getting this error right now.


```bash
Error: [sass-plugin] "onResolve" filter is not a valid Go regular expression: "^(?!.*.module.scss$).*.scss$"
```

**Comment by glromeo** [comment]
You don't have to go to the extent of providing mutually exclusive regexps...
this:
```javascript
plugins: [
            sassPlugin({
                filter: /\.module\.s?css$/,
                type: 'style',
                transform: postcssModules({})
            }),
            sassPlugin({
                filter: /\.s?css$/,
                type: 'style'
            }),
        ],
```
should work because the first regexp is more specific than the second, if it doesn't then we have a problem 😅

**Comment by rodoabad** [comment]
@glromeo oh. Well I was. thinking more of it being safer? So that if ever someone switches the two then it still works.

**Comment by glromeo** [comment]
I wouldn't try to achieve that... you can but at the cost of added complexity (...and making the build slower). Although being safe is a nice have code is code...be it in your app or your build scripts it is meant to be handled with care!
I am going to close this issue leaving a reference to it in the documentation hoping that it helps clarify this topic to other people approaching the plugin. Thank you for raising it!
