### ISSUE TITLE
Doesn't support path with non-ascii characters

### ISSUE THREAD

**Issue by MuTsunTsai** [glromeo/esbuild-sass-plugin#63]
As previously mentioned in issue #61, this plugin goes wrong if the imported .scss file makes another import, and if the full path of the latter file contains non-ascii characters. I believe this is a plugin-specific issue as this error doesn't occur with esbuild in general.

![image](https://user-images.githubusercontent.com/39870664/150888739-e3fe7c84-374b-4eed-bb7e-b055aa6b20a8.png)

As can be seen in the error message here, it somehow escapes the non-ascii characters internally, and therefore the file of course doesn't exists. This error doesn't occur if we only import one .scss file without any further importing inside it.

The current workaround is of course by putting the project in a path consists of ascii characters only, and then everything works fine.

**Comment by glromeo** [comment]
@MuTsunTsai yup...that was another interesting journey!

**Comment by glromeo** [comment]
I've just released v2.2.0 please have a try and let me know how it goes

**Comment by MuTsunTsai** [comment]
Damn that was fast! Confirmed issue fixed in v2.2.0 👍

**Comment by MuTsunTsai** [comment]
Did you seriously draw a picture just for this issue? LOL
