### ISSUE TITLE
SourceMap fix was removed in v2.1.0 

### ISSUE THREAD

**Issue by megaboich** [glromeo/esbuild-sass-plugin#66]
Hi, thanks for awesome plugin.
Recently I checked release notes and was amazed that you did a fix for sourcemaps exactly what I wanted.
But unfortunately the fix disappeared later from the code.

My config:
```js
const buildResult = await esbuild.build({
			entryPoints: ['./src/index.ts'],
			loader: {'.svg': 'dataurl'},
			format: 'cjs',
			target: ['es2019'],
			bundle: true,
			minify: true,
			sourcemap: true,
			outfile: './dist/demobook.min.js',
			plugins: [sassPlugin({
				type: 'css-text',
				style: 'compressed',
				sourcemap: false,
			})]
		});
```
As you can see I want to have sourcemap only for javascript, not for sass.

Please kindly refer to history below.

Original fix I refer to: https://github.com/glromeo/esbuild-sass-plugin/commit/b2382a7acd1d308cd69cef141f49878ee008b9a6

Was removed during this change: https://github.com/glromeo/esbuild-sass-plugin/commit/ab260903ed2e7c234ce0c395f119b8004eb5512e#diff-57716bc53661ccdb4571d571f1a5493294848965ae6068dbb3d9a1167d2cc1a6R59

Also it would be nice to have the same case for `sourcemap` (instead of `sourceMap`) option field name, the same like in esbuild.

**Comment by glromeo** [comment]
@megaboich thank you for spotting it! I am releasing v2.2.1 which will fix that.
I don't like `sourceMap` either but that's the syntax of SASS APIs and the options
that you pass to the plugin are a superset of the ones that `compileString` accepts
[where`sourceMap` is in camel case](
https://sass-lang.com/documentation/js-api/interfaces/StringOptionsWithImporter#sourceMap
)
