### ISSUE TITLE
Sourcemaps messed up when using @use (or @import)

### ISSUE THREAD

**Issue by Epskampie** [glromeo/esbuild-sass-plugin#69]
When using `@use` or `@import` the sourcemaps aren't correct anymore:

![Selection_008](https://user-images.githubusercontent.com/1692043/152196866-a6c7d5af-13f7-493c-ab34-d308acbb27d8.png)

I made a small reproduction again: https://github.com/Epskampie/esbuild-sass-sourcemaps

As you see, if you run `npm run esbuild:build` and open `with_use.html` in your browser the sourcemaps are wrong.
When your run `npm run sass:build` they are correct.

Also, in `without_use.html` they are correct in both cases.

The problem seems to occur only in the "root" sass file, if you @import deeper it starts working again.

Thanks for the great plugin BTW!

**Comment by glromeo** [comment]
Thank you for raising such a detailed issue! You will find a fix in 2.2.2... 

/* 22:22 of 02/02/2022 😆  */

**Comment by Epskampie** [comment]
Awesome! Thanks for the super quick fix. 🙏
