### ISSUE TITLE
Add support for the incremental/watch mode

### ISSUE THREAD

**Issue by rosenfeld** [glromeo/esbuild-sass-plugin#7]
It's now possible to tell esbuild which files are being watched for the incremental/watch mode to work. Just return the `watchFiles` in the `onResolve`. Take a look at this, for an example:

https://github.com/koluch/esbuild-plugin-sass/blob/main/index.ts#L45

Could you please support this in this plugin, so that it would also watch for changes to our sass files?

I'm switching from `esbuild-plugin-sass` to this one because I want to be able to use the style element creation approach for some of my CSS sources. But I miss the automatic rebuilding feature when the stylesheet changes. Could you please take a look at this?

**Comment by glromeo** [comment]
@rosenfeld please update to v1.3.0 
![bitmoji](https://sdk.bitmoji.com/render/panel/5b7bff30-d7cc-4141-9f91-d77fa135057f-774bf184-bc1c-4f48-a627-8361720afa10-v1.png?transparent=1&palette=1&width=246)

**Comment by rosenfeld** [comment]
Awesome, thanks!
