### ISSUE TITLE
using postcssModules make sass file cannot extract into a single css file

### ISSUE THREAD

**Issue by franckchen** [glromeo/esbuild-sass-plugin#78]
https://github.com/glromeo/esbuild-sass-plugin/blob/bc4452940e800ed18fa0761644e4f4ef3e4fddf6/src/utils.ts#L158
from the source code, when using this plugin with option postcssModulesPlugin make sass cannot extract into a single css file. is there anyway to solve this problem?i wannt to use css module and extract both

**Comment by tiagovtristao** [comment]
I'm facing the same issue, I wonder if this is a limitation with esbuild at the moment. Is this something that you know @glromeo ? Nice plugin by the way :-)

**Comment by glromeo** [comment]
Sorry guys what you ask is against `esbuild` design. In order for the css modules to be imported they have to be specified as 'js' for the loader and then `esbuild` leaves their handling to the plugin with no way for that css to be part of the compact bundle you want. I left this issue open while I was getting my head around the possibility of writing myself a bundling of all the styles module into a single one but the effort of such task (considering the issue with sourcemaps) puts it out of scope

**Comment by glromeo** [comment]
@ronkorland esbuild provides a callback for that https://esbuild.github.io/plugins/#on-end

```javascript
```

**Comment by yourivdlans** [comment]
I would also be interested in extracting the css to a separate file. @ronkorland would you mind sharing your approach?

**Comment by glromeo** [comment]
@franckchen @yourivdlans @tiagovtristao @ronkorland 
v2.7.0 brings, at long last, a solution to this CSS vs Js problem
while playing nicely with `esbuild` pipeline...have a try!
