### ISSUE TITLE
css not import  properly

### ISSUE THREAD

**Issue by rhu25** [glromeo/esbuild-sass-plugin#79]
hi team,

we used esbuild to build the package,

after build
those css not compiled
![Screen Shot 2022-05-30 at 11 10 13 AM](https://user-images.githubusercontent.com/16900386/170910358-0ece5567-5963-4f03-8718-837ee1e07aec.png)
![Screen Shot 2022-05-30 at 11 10 30 AM](https://user-images.githubusercontent.com/16900386/170910366-59816c38-48c3-4723-816c-38742c31c544.png)
thanks

**Comment by rhu25** [comment]
@glromeo

**Comment by glromeo** [comment]
Have you specified the option `cssImports` ?

**Comment by rhu25** [comment]
@glromeo

**Comment by rhu25** [comment]
@glromeo still not work with cssImports

```
import esbuild from 'esbuild'
import { nodeExternalsPlugin } from 'esbuild-node-externals'
import { sassPlugin } from 'esbuild-sass-plugin'

esbuild.build({
  entryPoints: ['src/index.ts'],
  outdir: 'dist/esm',
  bundle: true,
  sourcemap: true,
  minify: true,
  splitting: true,
  format: 'esm',
  target: 'esnext',
  plugins: [nodeExternalsPlugin(), sassPlugin({
    type: 'style',
    cssImports: true,
    nonce: 'window.__esbuild_nonce__'
  })],
})

esbuild.build({
  entryPoints: ['src/index.ts'],
  outdir: 'dist/cjs',
  bundle: true,
  sourcemap: true,
  minify: true,
  format: 'cjs',
  target: 'esnext',
  plugins: [nodeExternalsPlugin(), sassPlugin({
    type: 'style',
    cssImports: true,
    nonce: 'window.__esbuild_nonce__'
  })],
})
```
my scss file is like this 

```
@import '~normalize.css';
@import '~@blueprintjs/core/lib/css/blueprint.css';
@import '~@blueprintjs/icons/lib/css/blueprint-icons.css';
@import '~@blueprintjs/core/lib/scss/variables';


body {
  margin: 0;
  font-family: 'Segoe UI';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  height: 100vh;
  background-color: #f5f8fa;
}
```

after build
![Screen Shot 2022-05-31 at 10 00 09 AM](https://user-images.githubusercontent.com/16900386/171078064-503b188f-06ef-4e38-a8dd-f577dde2fedc.png)

**Comment by glromeo** [comment]
can you please run your example without `esbuild-node-externals` and see if that fixes your issue?

**Comment by rhu25** [comment]
@glromeo we cant remove it, after remove it, esbuild throw
```
(node:2618) UnhandledPromiseRejectionWarning: Error: Build failed with 105 errors:
node_modules/@blueprintjs/core/lib/esm/common/abstractComponent.js:17:23: ERROR: Could not resolve "react"
node_modules/@blueprintjs/core/lib/esm/common/abstractComponent2.js:17:23: ERROR: Could not resolve "react"
node_modules/@blueprintjs/core/lib/esm/common/abstractPureComponent.js:17:23: ERROR: Could not resolve "react"
node_modules/@blueprintjs/core/lib/esm/common/abstractPureComponent2.js:17:23: ERROR: Could not resolve "react"
node_modules/@blueprintjs/core/lib/esm/common/utils/reactUtils.js:16:23: ERROR: Could not resolve "react"

```

**Comment by glromeo** [comment]
the only suggestion I have is to invert the order of the plugins putting esbuild-sass-plugin first.
If that doesn't work create a github project replicating the issue

**Comment by glromeo** [comment]
I have reason to think that `esbuild-node-externals` prevents the resolution of cssImports and indeed it's not about the order it's about whether to avoid that plugin from messing with `@blueprintjs`  by adding it to the `options.allowList`
Then I don't understand what `~normalise.css` is supposed to be. `~` should prefix a node module there it prefixes just a file
I am going to close this issue due to lack of activity if you still want help please create a github project replicating the issue
