### ISSUE TITLE
Minifying CSS output

### ISSUE THREAD

**Issue by Beefers** [glromeo/esbuild-sass-plugin#85]
Hey!

I recently used this plugin in a project and noticed that when using "css-text" mode, the CSS output is not minified. This makes my bundle have newlines inside, which is... not ideal.

If possible, I'd like a way to minify the CSS output.
If there already is a way to do this, please point me there instead.

**Comment by lexisother** [comment]
I'd like to add my two cents here. I see that the options that are passable to the plugin do not include all options available to the sass compiler. This means you're locked down to what the plugin allows you to provide, no?

I don't see a clear way to pass custom options to the sass compiler, and I think it would be beneficial if that were added. 

Would make issues like this one extraneous, since people would be able to pass options on their own.

**Comment by glromeo** [comment]
@lexisother the options of the plugins are passed to the compiler
https://github.com/glromeo/esbuild-sass-plugin/blob/726b59f373e6af98f755068666e1cb3342f2b282/src/render.ts#L84
and the TS type is declared accordingly
https://github.com/glromeo/esbuild-sass-plugin/blob/726b59f373e6af98f755068666e1cb3342f2b282/src/index.ts#L7

@Beefers unfortunately the api doesn't provide minification but the plugin allows you to use postCSS
https://github.com/glromeo/esbuild-sass-plugin/blob/726b59f373e6af98f755068666e1cb3342f2b282/test/fixture/post-css/build.js#L19-L24
which in turn has a plugin for minification
https://github.com/jake-low/postcss-minify

the plugin can be configured this way
https://github.com/glromeo/esbuild-sass-plugin/blob/726b59f373e6af98f755068666e1cb3342f2b282/test/fixture/post-css/build.js#L7-L10

just replace those two entries in the example with `require("postcss-minify")`  and of course add your other options to the sassPlugin

**Comment by lexisother** [comment]
> the options of the plugins are passed to the compiler

Might be worth mentioning on the README. Thanks for the pointer! 👍🏻

**Comment by glromeo** [comment]
@lexisother there's just a bare example of postCSS in there... This is OpenSource, why don't you add an example section to it with this information? Happy to merge your contribution

**Comment by shellscape** [comment]
Ideally this plugin would allow esbuild's builtin minification pipeline to alter the output. Requiring PostCSS and another pass over the asset is wasteful in addition to burdensome for the user, a poor DX for users that wish to minify the output from this plugin.

**Comment by glromeo** [comment]
@shellscape feel free to branch it and reshape it the way you want it

**Comment by glromeo** [comment]
@shellscape you might find interesting the change to CSS modules that landed in v2.7.0
`type: 'style'` is no longer required and all CSS content flows into `esbuild` now
