### ISSUE TITLE
require vs import on build script

### ISSUE THREAD

**Issue by ivanyv** [glromeo/esbuild-sass-plugin#88]
Just starting to dabble with esbuild, and I notice your setup instructions are different than other plugins.

When I use `import { sassPlugin } from 'esbuild-sass-plugin'`, I get `SyntaxError: Cannot use import statement outside a module`.

If I try to use `require` instead, I get:
```
(node:32315) UnhandledPromiseRejectionWarning: Error: Build failed with 1 error:
.../node_modules/esbuild/lib/main.js:785:14: ERROR: Plugin at index 1 is missing a name
```

Here's the build script:
```javascript
const vuePlugin = require('esbuild-vue')
// const sassPlugin = require('esbuild-sass-plugin')
// import { sassPlugin } from 'esbuild-sass-plugin'

require('esbuild').build({
  entryPoints: ["src/main.js"],
  bundle: true,
  outfile: "dist/main.js",
  logLevel: "info",
  plugins: [vuePlugin(), sassPlugin()],
  define: {
    "process.env.NODE_ENV": JSON.stringify("development"),
  },
});
```

Any help with the correct way to set it up would be appreciated.

**Comment by glromeo** [comment]
@ivanyv the `require` examples in the README.md are in this form
```
const {sassPlugin} = require('esbuild-sass-plugin')
```
meaning get the sassPlugin from the module exports.

I appreciate the earlier examples don't explain what you need to be able to use the `import`
keyword but that's general [node modules](https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1) knowledge that I have to give for granted.

**Comment by ivanyv** [comment]
@glromeo I figured it must have been something simple.

> I appreciate the earlier examples don't explain what you need to be able to use the import
keyword but that's general [node modules](https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1) knowledge that I have to give for granted.

Agreed, thanks for helping anyway!
