### ISSUE TITLE
Documentation redirects to Armin van Buuren DJ set

### ISSUE THREAD

**Issue by abr-storm** [glromeo/esbuild-sass-plugin#89]
I was trying to learn about the `loadPaths` option, but when clicking the link in the documentation I was redirected to a performance by Armin van Buuren at Creamfields 2019 (Hong Kong).

Is this intentional? If not, where was this link meant to go?

**Comment by glromeo** [comment]
Thank you for pointing that out @abr-storm, what happened is that a shortened URL was used in the README and that expired and pointed to somewhere else... I just fixed it and I hope it helps!
