### ISSUE TITLE
node-sass dependency

### ISSUE THREAD

**Issue by eknkc** [glromeo/esbuild-sass-plugin#9]
Hi!

Is there a particular reason that `node-sass` is a peer dependency? npm 7 now installs peer dependencies automatically so the plugin installs both sass and node-sass.

Can we remove it if it is not required for the plugin functionality?

Thanks!

**Comment by glromeo** [comment]
Thank you for your heads up @eknkc ...I definitely don't want that behaviour! I am going to remove node-sass peer dependency right away!

**Comment by eknkc** [comment]
Thanks a lot!
