### ISSUE TITLE
Not detect .scss extension

### ISSUE THREAD

**Issue by Julian-Carelli** [glromeo/esbuild-sass-plugin#90]
The problem is when I try to do a build with **esbuilt**, breaks because the plugin have issues for detect files without extension like ****/index**. For example in this case the plugin don't know detect the file's extension because have 2 with the same name (index)

<img width="310" alt="Captura de Pantalla 2022-08-08 a la(s) 18 06 36" src="https://user-images.githubusercontent.com/56791326/183514837-4ca7da0b-a750-4284-ab17-7d37e037c939.png">

in this way call to file: 

<img width="430" alt="Captura de Pantalla 2022-08-08 a la(s) 18 09 59" src="https://user-images.githubusercontent.com/56791326/183515201-bdd9266c-3ff9-4c97-aac5-791571bad970.png">

**Comment by glromeo** [comment]
sorry to contradict but the plugin is built to handle this 
https://github.com/glromeo/esbuild-sass-plugin/blob/75d27ec374373e796738fe35f987f7d09acf9fd8/src/render.ts#L43-L46
and I have verified this personally, I am going to close this but if you really want help
please create a github repo that reproduce the issue and I will look into it

**Comment by stevebeauge** [comment]
I had the same issue, especially with scss files inside dependencies.

I worked around the issue using importMapper

````js
    plugins: [sassPlugin({
        importMapper: (path) => {
            if (!path.endsWith('.scss')) return path + ".scss";
            return path;
        }

    })],
````
