### ISSUE TITLE
Incorectly resolves imports 

### ISSUE THREAD

**Issue by linasburneika** [glromeo/esbuild-sass-plugin#91]
If you import sass from a library that also has .js file with the same name as sass, the default require.resolve method picks js instead.
For example:
@import "~@my/package/lib/tool";

It causes a parsing failure if both files exist in the library: lib/tool.scss and lib/tool.js

A quick workaround is to use "prefer" option which uses resolve from browserify, which allows to restrict extensions, like this in utils file:

```
const opts = {
    paths: ['.', ...loadPaths],
    extensions: ['scss', 'sass'],
    readPackageSync(readFileSync, pkgfile) {
        let cached = cache[pkgfile];
        if (!cached) {
            const pkg = JSON.parse(readFileSync(pkgfile));
            cached = cache[pkgfile] = { main: pkg[prefer] || pkg.main };
        }
        return cached;
    }
};
```

**Comment by glromeo** [comment]
yup! that's indeed an issue... one day I will carve out the time to come up with my own resolver loosely based on browserify and get rid of require.resolve in the meanwhile I have an idea for a quick fix...

**Comment by glromeo** [comment]
v2.3.2 should address this, and only this, case... I don't have time to cover it with a test, can you please confirm?

**Comment by linasburneika** [comment]
It's a really rough patch, but does the job ;) No more errors. Thanks for a blazing fast reply!
